---
provisioner:
  name: salt_solo
  formula: {{cookiecutter.repo_name.split('-')[0]}}
  state_top:
    base:
      '*':
        - {{cookiecutter.repo_name.split('-')[0]}}
  omnibus_cachier: true

platforms:
  - name: vagrant-centos-7
    driver_plugin: vagrant
    driver_config:
      vagrantfile_erb: "kitchenvagrant/Vagrantfile.erb"
      cachier:
        scope: "box"
      customize:
        memory: 1024
      box: "rocketman110us/centos71-saltminion"

suites:
  - name: default
