source 'https://rubygems.org'

gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-salt', :git => 'https://github.com/simonmcc/kitchen-salt.git'
gem 'rake'
gem 'serverspec'

# For testing on AWS EC2
gem 'unf'
gem 'kitchen-ec2'
